[tools]
go = "1.25.7"
"go:gotest.tools/gotestsum" = "latest"
"go:golang.org/x/pkgsite/cmd/pkgsite" = "latest"
"github:golang-migrate/migrate" = "latest"
"github:sqlc-dev/sqlc" = "latest"
"github:golangci/golangci-lint" = "latest"
